{{- if .Values.ingress.enabled }}
{{- $webService := include "go-guess.webDeploymentName" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go-guess.fullname" . }}
  labels:
    {{- include "go-guess.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.tenants }}
        - {{ printf "%s.%s" . $.Values.domain | quote }}
        {{- end }}
      secretName: {{ include "go-guess.tlsSecretName" . }}
  {{- end }}
  rules:
    {{- range .Values.tenants }}
    - host: {{ printf "%s.%s" . $.Values.domain | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $webService }}
                port:
                  number: {{ $.Values.web.service.port }}
    {{- end }}
{{- end }}