{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-guess.rabbitmqName" . }}
  labels:
    {{- include "go-guess.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  clusterIP: None
  selector:
    {{- include "go-guess.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
{{- end }}
