image:
  tag: latest
  pullPolicy: IfNotPresent

app:
  environment: production
  frontendURL: https://goguess.urpi.be

service:
  type: NodePort
  nodePort: 31374

ingress:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi

postgresql:
  persistence:
    enabled: true
    size: 20Gi

rabbitmq:
  persistence:
    enabled: true
    size: 8Gi
